gimbal_transform_node:
  ros__parameters:

    # ----------------------------
    # Coordinate Frame Settings
    # ----------------------------
    coordinate_frame: "UTM"
    utm_zone: 32
    northern_hemisphere: true

    # If coordinate_frame == "LOCAL", define a base lat/lon/alt
    base_lat: 51.445
    base_lon: 8.037
    base_alt: 0.0

    # ----------------------------
    # Topic & Service Names (MANDATORY) (From the wrapper)
    # ----------------------------
    gps_position_topic: "/wrapper/psdk_ros2/gps_position_fused"
    imu_topic: "/uav/imu/data"
    gimbal_center_topic: "/uav/gimbal_center_position"

    # ----------------------------
    # Gimbal Control Topics (created for the project)
    # ----------------------------
    gimbal_command_topic: "/wrapper/psdk_ros2/gimbal_rotation"
    set_target_service_name: "/geogimbal/set_target"

    # ----------------------------
    # Gimbal Transform Flag
    # If true => Apply DH chain to get gimbal center
    # If false => Just convert GPS to UTM & publish
    # ----------------------------
    apply_gimbal_transform: true
